### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by zakaria-chahboun** [6f5/rtl-arabic#1]
First of all السلام عليكم ورحمة الله
Thank you for this initiative!
i have some issues:
- Fist one
i tried your example (أحبكم) but when i use it in my project it shows like that:
![Screenshot from 2021-07-30 19-07-08](https://user-images.githubusercontent.com/18173275/127695121-6de63728-1fc9-450e-af22-71579db1f6dd.png)
- second one:
when i tried this exapmle
```js
const convertedText = rtlArabic("كيف الحال؟");
```
it gives me this issue line:
```shell
TypeError: Cannot read property 'isolated' of undefined
   word_.push(letter.isolated);
in  rtl-arabic/utils.js line 135
```

You can visit this link to try my example online (with NPM RunKit):
https://runkit.com/embed/io4eghompg68

**Comment by 6f5** [comment]
Yeah, that was expected. I will revert to the previous version for now and it should work fine. I'm still working on it to make it work with all the Arabic characters.  Try again in an hour or so and it should work.

**Comment by 6f5** [comment]
> First of all السلام عليكم ورحمة الله
> Thank you for this initiative!
> i have some issues:
> 
> * Fist one
>   i tried your example (أحبكم) but when i use it in my project it shows like that:
>   ![Screenshot from 2021-07-30 19-07-08](https://user-images.githubusercontent.com/18173275/127695121-6de63728-1fc9-450e-af22-71579db1f6dd.png)
> * second one:
>   when i tried this exapmle
> 
> ```js
> const convertedText = rtlArabic("كيف الحال؟");
> ```
> 
> it gives me this issue line:
> 
> ```shell
> TypeError: Cannot read property 'isolated' of undefined
>    word_.push(letter.isolated);
> in  rtl-arabic/utils.js line 135
> ```
> 
> You can visit this link to try my example online (with NPM RunKit):
> https://runkit.com/embed/io4eghompg68

I reverted it to the previous version. It should now work just uninstall and reinstall the package and if it still doesn't work try again in half an hour or so. It will support the majority of the characters but not all of them. I'll make it support 99% of them in a few weeks or when I get time.

**Comment by 6f5** [comment]
> First of all السلام عليكم ورحمة الله
> Thank you for this initiative!
> i have some issues:
> 
> * Fist one
>   i tried your example (أحبكم) but when i use it in my project it shows like that:
>   ![Screenshot from 2021-07-30 19-07-08](https://user-images.githubusercontent.com/18173275/127695121-6de63728-1fc9-450e-af22-71579db1f6dd.png)
> * second one:
>   when i tried this exapmle
> 
> ```js
> const convertedText = rtlArabic("كيف الحال؟");
> ```
> 
> it gives me this issue line:
> 
> ```shell
> TypeError: Cannot read property 'isolated' of undefined
>    word_.push(letter.isolated);
> in  rtl-arabic/utils.js line 135
> ```
> 
> You can visit this link to try my example online (with NPM RunKit):
> https://runkit.com/embed/io4eghompg68

And for the error that showed up its because it doesn't support the punctuations yet like the question symbol "?".

**Comment by zakaria-chahboun** [comment]
@6f5
I reuse it but unfortunately the same issue!
In the image bellow, You see the 1st result by `rtl-arabic` and 2nd result by http://www.arabic-text.com/

![Screenshot from 2021-08-02 19-24-10](https://user-images.githubusercontent.com/18173275/127908705-3590bd75-e7f2-4ff4-8a74-32075cff191b.png)

**Comment by 6f5** [comment]
All major issues have been resolved.
