### ISSUE TITLE
More harokat

### ISSUE THREAD

**Issue by Nurutomo** [6f5/rtl-arabic#2]
Harokat are from `\u064b` to `\u0653`

*Reference: https://en.wikipedia.org/wiki/Arabic_script_in_Unicode#Character_table*

**Comment by 6f5** [comment]
Harakat support has been implemented. Give it a try.

> Harokat are from `\u064b` to `\u0653`
> 
> _Reference: https://en.wikipedia.org/wiki/Arabic_script_in_Unicode#Character_table_

Harakat support has been implemented. Give it a try.
