### ISSUE TITLE
Issue when running server 

### ISSUE THREAD

**Issue by andyglez96** [6f5/rtl-arabic#3]
Hello,

I'm having an issue when using this library. See the attached picture

![image](https://user-images.githubusercontent.com/88163491/203036595-69972942-cded-40ad-a280-354755ecf0f2.png)

My server doesn't start

**Comment by 6f5** [comment]
Hello Andy,

Please Provide the Steps To Reproduce this error, the current behavior and the behavior you expected. Also, what version of node are you using?
